# Generated by Django 5.0.2 on 2024-02-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('acronym', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('registration', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('link_type', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('photo_url', models.URLField(unique=True)),
                ('campus', models.ForeignKey(db_column='campus_acronym', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.campus')),
                ('course', models.ForeignKey(db_column='course_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True)),
                ('email_type', models.CharField(db_column='type', max_length=15)),
                ('user', models.ForeignKey(db_column='user_registration', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(db_column='user_registration', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
