# Generated by Django 5.0.2 on 2024-02-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(default='/base/static/global/img/news_cover_placeholder.jpg', upload_to=''),
        ),
    ]
