# Generated by Django 5.0.6 on 2024-05-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('editions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='editions.edition'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team', to='competitions.match'),
        ),
        migrations.AddField(
            model_name='matchteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_team', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(related_name='matches', through='competitions.MatchTeam', to='teams.team'),
        ),
        migrations.AddField(
            model_name='sportcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_category', to='competitions.category'),
        ),
        migrations.AddField(
            model_name='sportcategory',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_category', to='competitions.sport'),
        ),
        migrations.AddField(
            model_name='sport',
            name='categories',
            field=models.ManyToManyField(related_name='sports', through='competitions.SportCategory', to='competitions.category'),
        ),
        migrations.AddField(
            model_name='match',
            name='sport_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='competitions.sportcategory'),
        ),
        migrations.AddField(
            model_name='testteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='testteam',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='teams',
            field=models.ManyToManyField(related_name='tests', through='competitions.TestTeam', to='teams.team'),
        ),
    ]
