# Generated by Django 5.0.6 on 2024-05-28 12:42

import helpers.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('collection_type', models.CharField(choices=[('document', 'Documento'), ('image', 'Imagem')], db_column='type', max_length=8)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=helpers.model.generate_collection_cover_path)),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=75, unique=True)),
            ],
        ),
    ]
