# Generated by Django 5.0.2 on 2024-02-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('edition_type', models.CharField(db_column='type', max_length=10)),
                ('theme', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(db_column='course_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.course')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('classes', models.ManyToManyField(to='editions.class')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.BooleanField()),
                ('competition', models.ForeignKey(db_column='competition_id', on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='editions.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=None, null=True)),
                ('classification', models.PositiveSmallIntegerField(default=None, null=True)),
                ('edition', models.ForeignKey(db_column='edition_year', on_delete=django.db.models.deletion.CASCADE, to='editions.edition')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='editions.team')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='teams',
            field=models.ManyToManyField(through='editions.TeamEdition', to='editions.team'),
        ),
    ]
