from django.db import models
from editions.models import Course


class User(models.Model):
    registration = ...
    campus = ...  # Change db_column("campus_acronym")
    course = ...  # Change db_column("course_id")
    full_name = ...
    first_name = ...
    last_name = ...
    cpf = ...
    link_type = ...
    sex = ...
    date_of_birth = ...
    photo_url = ...


class Email(models.Model):
    user = ...  # Change db_column("user_registration")
    address = ...
    email_type = ...  # Change db_column("type")


class Campus(models.Model):
    acronym = ...
    name = ...


class Administrator(models.Model):
    user = ...  # Change db_column("user_registration")
