# Generated by Django 5.0.6 on 2024-05-28 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('year', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('edition_type', models.CharField(choices=[('classes', 'Confronto entre turmas'), ('courses', 'Confronto entre cursos')], db_column='type', max_length=30)),
                ('theme', models.CharField(blank=True, max_length=100, null=True)),
                ('sports', models.ManyToManyField(related_name='editions', to='competitions.sport')),
            ],
        ),
        migrations.CreateModel(
            name='EditionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0, null=True)),
                ('edition', models.ForeignKey(db_column='edition_year', on_delete=django.db.models.deletion.CASCADE, related_name='edition_team', to='editions.edition')),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='edition_team', to='teams.team')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='teams',
            field=models.ManyToManyField(related_name='editions', through='editions.EditionTeam', to='teams.team'),
        ),
    ]
