# Generated by Django 5.0.1 on 2024-01-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(max_length=225, unique=True)),
                ('creation_date', models.DateField(blank=True)),
                ('update_date', models.DateField(blank=True)),
                ('administrator', models.ForeignKey(db_column='administrator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.administrator')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.PositiveBigIntegerField()),
                ('collection', models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, to='archive.collection')),
            ],
        ),
    ]
