# Generated by Django 5.0.2 on 2024-02-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(upload_to=''),
        ),
    ]
