# Generated by Django 5.0.2 on 2024-02-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_collection_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover',
            field=models.ImageField(default='/base/static/global/img/collection_cover_placeholder.jpg', upload_to=''),
        ),
    ]
