# Generated by Django 5.0.1 on 2024-02-06 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('editions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='edition',
            field=models.ForeignKey(db_column='edition_year', on_delete=django.db.models.deletion.CASCADE, to='editions.edition'),
        ),
        migrations.AddField(
            model_name='competition',
            name='teams',
            field=models.ManyToManyField(through='editions.TeamCompetition', to='editions.team'),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='competitions.category'),
        ),
        migrations.AddField(
            model_name='testorsport',
            name='sport',
            field=models.OneToOneField(db_column='sport_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.sport'),
        ),
        migrations.AddField(
            model_name='testorsport',
            name='test',
            field=models.OneToOneField(db_column='test_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competitions.test'),
        ),
        migrations.AddField(
            model_name='competition',
            name='test_or_sport',
            field=models.ForeignKey(db_column='test_or_sport_id', on_delete=django.db.models.deletion.CASCADE, to='competitions.testorsport'),
        ),
    ]
