# Generated by Django 5.0.1 on 2024-02-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='date_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
