# Generated by Django 5.0.2 on 2024-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
